site_name: minipaxtar
site_description: "Lightweight, single-header C TAR library"
site_url: "https://imvulpi.github.io/minipaxtar/"
repo_url: "https://github.com/imvulpi/minipaxtar"
repo_name: "minipaxtar"
use_directory_urls: true

theme:
  name: terminal
  palette: dark
  language: en
  features:
    - navigation.indexes           # Section headers act as clickable index pages
    - navigation.sections          # Group pages into clear visual sidebar blocks
    - navigation.expand            # Keeps sections expanded by default
    - navigation.top               # Adds a "Back to Top" smooth scroll button
    - navigation.tracking          # Updates URL anchor as user scrolls
    - header.autohide              # Auto-hides header bar when scrolling down
    - content.code.copy            # Adds a 1-click copy button to all code blocks
    - content.code.annotate        # Allows inline comment callouts in code blocks
plugins:
  - search 
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - tables
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css
  - stylesheets/terminal-custom.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/c.min.js
  - javascripts/init-hljs.js
nav:
  - Overview:
      - Getting Started: index.md
      - Quickstart Guide: overview/quickstart.md
      - Reading Archives: overview/reading.md
      - Writing Archives: overview/writing.md
      - Extracting Files: overview/extracting.md
      - Integrating it: overview/integration.md
  - Features & Guides:
      - PAX vs USTAR Format: guides/pax-format.md
      - Configuration Flags: guides/config-defines.md
      - Status/Error Codes: guides/status-codes.md
      - Error Handling: guides/error-handling.md
  - API Reference:
    - Groups: api/index_groups.md
    - Structures: api/index_classes.md
    - Files: api/index_files.md