from pathlib import Path
import re
import sys

_LINK_RE = re.compile(
    r"(\[[^\]]+\]\([^)#]+)\.md((?:#[^)]+)?\))"
)

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent

def strip_md_extensions(api_dir: Path) -> int:
    """
    Remove `.md` extensions from Markdown links in all .md files
    under `api_dir`.

    Returns:
        Number of files modified.
    """
    modified = 0

    for md_file in api_dir.rglob("*.md"):
        original = md_file.read_text(encoding="utf-8")

        updated = _LINK_RE.sub(r"\1\2", original)

        if updated != original:
            md_file.write_text(updated, encoding="utf-8")
            modified += 1

    return modified

def main():
    try:
        print("Removing `.md` extensions from .md files generated by Doxybook2.")
        strip_md_extensions(ROOT / "docs" / "api")
    except Exception as e:
        print(f"Adjusting documentation links failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()